% Create a dipole antenna backed with reflectorCylindrical
% Generated by MATLAB(R) 9.13 and Antenna Toolbox 5.3.
% Generated on: 08-Nov-2022 10:03:28

%% Antenna Properties 

antennaObject = design(reflectorCylindrical('Exciter', dipole), 1000*1e6);
% Show
figure;
show(antennaObject) 

%% Antenna Analysis 
% Define plot frequency 
plotFrequency = 1*1e9;
% Define frequency range 
freqRange = (900:10:1100)*1e6;
% Reference Impedance 
refImpedance = 50;
% impedance
figure;
impedance(antennaObject, freqRange)
% sparameter
figure;
s = sparameters(antennaObject, freqRange, refImpedance); 
rfplot(s)
% pattern
figure;
pattern(antennaObject, plotFrequency)
% azimuth
figure;
patternAzimuth(antennaObject, plotFrequency, 0, 'Azimuth', 0:5:360)
% elevation
figure;
patternElevation(antennaObject, plotFrequency,0,'Elevation',0:5:360)
% current
figure;
current(antennaObject, plotFrequency)

